#!/usr/bin/env bash
# Generates Version.swift from package.json version.
# Called by the pre-commit hook automatically.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VERSION=$(node -p "require('$ROOT_DIR/package.json').version")

TOOLKIT_VERSION=""
TOOLKIT_PKG="$ROOT_DIR/.build/checkouts/een-swift-toolkit/package.json"
if [ ! -f "$TOOLKIT_PKG" ]; then
  # Try DerivedData SPM checkout used by xcodebuild
  for candidate in /tmp/ObservationCompanion-build/SourcePackages/checkouts/een-swift-toolkit/package.json \
                   "$HOME/Library/Developer/Xcode/DerivedData"/ObservationCompanion-*/SourcePackages/checkouts/een-swift-toolkit/package.json; do
    if [ -f "$candidate" ]; then
      TOOLKIT_PKG="$candidate"
      break
    fi
  done
fi
if [ -f "$TOOLKIT_PKG" ]; then
  TOOLKIT_VERSION=$(node -p "require('$TOOLKIT_PKG').version")
fi

DIR="$ROOT_DIR/ObservationCompanion"
if [ -d "$DIR" ]; then
  cat > "$DIR/Version.swift" << EOF
// Auto-generated by scripts/generate-version.sh — do not edit manually
let toolkitVersion = "$VERSION"
let eenSwiftToolkitVersion = "${TOOLKIT_VERSION:-unknown}"
EOF
fi
